apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  # Add other non-sensitive configuration here
  # Example:
  # CORS_ORIGIN: "https://yourapp.com" 