apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  # Secrets must be base64 encoded
  # Example: echo -n "your-secret-value" | base64
  MONGODB_URI: {{ .Values.secrets.mongodbUri | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | b64enc | quote }}
  # Add other sensitive data here 