apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-mcp-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smart-mcp-server
  template:
    metadata:
      labels:
        app: smart-mcp-server
    spec:
      containers:
        - name: server
          image: your-docker-registry/smart-mcp-server:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: server-config
            - secretRef:
                name: server-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
