apiVersion: v1
kind: Service
metadata:
  name: smart-mcp-server-service
spec:
  selector:
    app: smart-mcp-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
